name: Flake Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Root Flake
        run: nix flake check

      - name: Check Template Flake
        run: |
          cd template
          sed -i 's|url = "github:richen604/hydenix"|url = "path:../"|' flake.nix
          nix flake check
          git checkout flake.nix
          rm -f flake.lock
          